In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))
        break

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasetiitisocac/chimpanzee/12e3711a55.jpg
/kaggle/input/datasetiitisocac/butterfly/6a09b0f37d.jpg
/kaggle/input/datasetiitisocac/dog/41f5881bb6.jpg
/kaggle/input/datasetiitisocac/caterpillar/21b68b5df1.jpg
/kaggle/input/datasetiitisocac/elephant/18d2849164.jpg
/kaggle/input/datasetiitisocac/cow/85ebd9b6f4.jpg
/kaggle/input/datasetiitisocac/dolphin/8e8ec91d3e.jpg
/kaggle/input/datasetiitisocac/sparrow/2f238b1987.jpg
/kaggle/input/datasetiitisocac/cat/4815f8dfaa.jpg
/kaggle/input/datasetiitisocac/deer/1bd462a4d8.jpg


In [2]:
import glob
import shutil
import matplotlib.pyplot as plt


In [3]:
import tensorflow as tf

In [4]:
import cv2

In [5]:
import random
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

In [6]:
path= '../input/datasetiitisocac'
Categories=['butterfly','cat','caterpillar','chimpanzee','cow','deer','dog','dolphin','elephant','sparrow']

In [7]:
from tensorflow.keras.applications.inception_v3 import InceptionV3
from tensorflow.keras.applications.inception_v3 import preprocess_input
from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.image import img_to_array
from sklearn.cluster import KMeans
import pandas as pd
import numpy as np
from tqdm import tqdm
import os
import shutil

In [8]:
#Defining a function to extract relevant features of the images using pre-trained model Inception V3

In [9]:

def image_feature(path):
    model= InceptionV3(weights='imagenet',include_top= False)
    features=[];
    img_name=[];
    for folder in os.listdir(path):
        sub_path=path+"/"+folder
        for img in os.listdir(sub_path):
            image_path=sub_path+"/"+img
            img_arr=cv2.imread(image_path)
            img_arr=cv2.resize(img_arr,(150,150))
            img_arr=np.expand_dims(img_arr,axis=0)
            img_arr=preprocess_input(img_arr)
            feat=model.predict(img_arr)
            feat=feat.flatten()
            features.append(feat)
            img_name.append(img)
    return features,img_name
        
        

In [10]:
path= '../input/datasetiitisocac'
img_features,img_names=image_feature(path)


2022-07-25 17:04:02.559213: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


87924736/87910968 [==============================] - 3s 0us/step


2022-07-25 17:04:09.013340: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


In [11]:
import pandas as pd

In [12]:
#Creating a pandas dataframe to store columns of the two lists

In [13]:
make_list=pd.DataFrame(list(zip(img_names,img_features)),columns=['Img_Names','Img_features'])

In [14]:
#Shuffling the dataset so that the model does not learn anything from the order of the images

In [15]:
shuffled= make_list.sample(frac=1)
print(shuffled.head())

          Img_Names                                       Img_features
266  8c2d171b9d.jpg  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.88439775...
503  8aefee4c2c.jpg  [0.0, 0.22593242, 0.0, 0.5672823, 2.188591, 0....
40   38c1bc9469.jpg  [0.0, 0.0, 0.0, 0.0, 1.7253847, 0.45103508, 4....
93   4862ffccc5.jpg  [1.8370278, 0.59486425, 3.6260784, 4.6751213, ...
214  0f651f75c0.jpg  [0.31184146, 1.0264263, 0.0, 1.3285662, 2.1059...


In [16]:
img_features

[array([0.        , 0.        , 0.9276053 , ..., 0.        , 0.        ,
        0.37998584], dtype=float32),
 array([0.        , 0.        , 0.35245892, ..., 0.        , 0.        ,
        1.5007722 ], dtype=float32),
 array([0.       , 0.450873 , 0.       , ..., 0.       , 0.       ,
        3.8147137], dtype=float32),
 array([0.       , 1.0530751, 0.       , ..., 0.       , 0.       ,
        1.046347 ], dtype=float32),
 array([0.83330715, 0.8334007 , 0.        , ..., 1.5255708 , 0.        ,
        1.4651625 ], dtype=float32),
 array([0.71160626, 1.0691954 , 0.        , ..., 1.974716  , 0.04386184,
        2.4972243 ], dtype=float32),
 array([0.       , 0.       , 0.       , ..., 0.       , 0.5045335,
        0.       ], dtype=float32),
 array([2.2868316 , 0.2775689 , 0.20049024, ..., 0.23900619, 0.452537  ,
        0.        ], dtype=float32),
 array([0.49659654, 1.8629706 , 0.        , ..., 1.7132261 , 2.6959057 ,
        0.7946845 ], dtype=float32),
 array([1.6472292 , 1.378905

In [17]:
shuffled_list= list(shuffled['Img_features'])
shuffled_list[0]

array([0.     , 0.     , 0.     , ..., 0.     , 0.     , 4.06544],
      dtype=float32)

In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(shuffled_list)
shuffled_list_sc = sc.transform(shuffled_list)


In [19]:
from sklearn.decomposition import PCA

In [20]:
pca = PCA()

In [21]:
shuffled_list_pca=pca.fit_transform(shuffled_list_sc)

In [22]:
#Creating Clusters
#Implementing kMeans clustering algo
k = 10
clusters= KMeans(n_clusters=10, random_state=0, init='k-means++', max_iter=300, n_init=10)

clusters.fit_predict(shuffled_list_pca)

array([0, 9, 4, 1, 1, 2, 2, 1, 2, 5, 5, 1, 1, 1, 4, 5, 0, 2, 8, 3, 8, 2,
       8, 9, 1, 3, 4, 9, 5, 1, 3, 1, 1, 1, 1, 3, 4, 8, 8, 5, 1, 0, 2, 1,
       9, 1, 8, 4, 1, 9, 1, 4, 2, 5, 1, 5, 1, 4, 6, 5, 5, 1, 8, 1, 1, 1,
       6, 2, 8, 1, 7, 1, 9, 9, 2, 1, 2, 4, 3, 1, 3, 1, 6, 8, 8, 7, 3, 6,
       1, 6, 0, 3, 4, 5, 4, 4, 5, 0, 1, 5, 3, 3, 1, 7, 8, 8, 3, 1, 8, 1,
       1, 1, 1, 2, 1, 0, 4, 4, 3, 9, 1, 6, 1, 1, 1, 3, 1, 0, 4, 0, 2, 7,
       3, 2, 0, 5, 1, 3, 1, 1, 0, 2, 5, 8, 1, 9, 1, 1, 3, 0, 8, 3, 1, 1,
       5, 3, 8, 2, 1, 7, 0, 2, 7, 1, 3, 2, 8, 5, 1, 0, 6, 2, 3, 0, 0, 9,
       5, 1, 4, 4, 1, 0, 3, 2, 4, 4, 2, 2, 0, 1, 1, 2, 0, 1, 8, 9, 0, 9,
       1, 1, 5, 2, 1, 4, 5, 5, 1, 0, 7, 8, 3, 3, 8, 1, 5, 4, 8, 8, 1, 4,
       1, 1, 0, 7, 3, 2, 9, 5, 6, 1, 1, 9, 0, 5, 1, 2, 2, 1, 2, 0, 1, 1,
       9, 0, 1, 0, 1, 2, 7, 1, 3, 9, 1, 5, 0, 0, 1, 1, 1, 0, 9, 4, 0, 7,
       3, 0, 2, 2, 1, 7, 8, 0, 8, 4, 5, 3, 2, 2, 2, 3, 0, 2, 1, 9, 1, 3,
       1, 7, 1, 9, 2, 9, 7, 8, 1, 6, 6, 4, 8, 4, 7,

In [23]:
img_names_shuffled_list= list(shuffled['Img_Names'])
image_cluster = pd.DataFrame(img_names_shuffled_list,columns=['image'])
image_cluster["clusterid"] = clusters.labels_
image_cluster 

image  clusterid
0    8c2d171b9d.jpg          0
1    8aefee4c2c.jpg          9
2    38c1bc9469.jpg          4
3    4862ffccc5.jpg          1
4    0f651f75c0.jpg          1
..              ...        ...
595  3c19f4785b.jpg          1
596  4e79b3fbec.jpg          1
597  128fc39904.jpg          8
598  6b4c626340.jpg          0
599  28dba6a409.jpg          2

[600 rows x 2 columns]

In [24]:
image_cluster['image'][:100]

0     8c2d171b9d.jpg
1     8aefee4c2c.jpg
2     38c1bc9469.jpg
3     4862ffccc5.jpg
4     0f651f75c0.jpg
           ...      
95    52b631552c.jpg
96    2cb580feff.jpg
97    63e4606329.jpg
98    810c695037.jpg
99    75fefe8441.jpg
Name: image, Length: 100, dtype: object

In [25]:
image_cluster['clusterid'][:100]

0     0
1     9
2     4
3     1
4     1
     ..
95    4
96    5
97    0
98    1
99    5
Name: clusterid, Length: 100, dtype: int32

In [26]:
#image_cluster.plot.scatter(x='image',y='clusterid', figsize=(14,21))

In [27]:
image_cluster['image'][0]

'8c2d171b9d.jpg'

In [28]:

# Images will be seperated according to cluster they belong
# Made folder to seperate images

In [29]:
# Made folder to seperate images
os.mkdir('clusterr0')


In [30]:
for i in range(len(image_cluster)):
    if image_cluster['clusterid'][i]==0:
        for dirname, _, filenames in os.walk('../input/datasetiitisocac'):
            for filename in filenames:
                if (filename==image_cluster['image'][i]):
                    shutil.copy(os.path.join(dirname,image_cluster['image'][i]), os.path.join('clusterr0',image_cluster['image'][i]))
    

In [31]:
os.mkdir('clusterr1')


In [32]:
for i in range(len(image_cluster)):
    if image_cluster['clusterid'][i]==1:
        for dirname, _, filenames in os.walk('../input/datasetiitisocac'):
            for filename in filenames:
                if (filename==image_cluster['image'][i]):
                    shutil.copy(os.path.join(dirname,image_cluster['image'][i]), os.path.join('clusterr1',image_cluster['image'][i]))
    

In [33]:
os.mkdir('clusterr2')


In [34]:
for j in range(len(image_cluster)):
    if image_cluster['clusterid'][j]==2:
        for dirname, _, filenames in os.walk('../input/datasetiitisocac'):
            for filename in filenames:
                if (filename==image_cluster['image'][j]):
                    shutil.copy(os.path.join(dirname,image_cluster['image'][j]), os.path.join('clusterr2',image_cluster['image'][j]))
    

In [35]:
os.mkdir('clusterr3')


In [36]:
for k in range(len(image_cluster)):
    if image_cluster['clusterid'][k]==3:
        for dirname, _, filenames in os.walk('../input/datasetiitisocac'):
            for filename in filenames:
                if (filename==image_cluster['image'][k]):
                    shutil.copy(os.path.join(dirname,image_cluster['image'][k]), os.path.join('clusterr3',image_cluster['image'][k]))
    

In [37]:
os.mkdir('clusterr4')


In [38]:
for k in range(len(image_cluster)):
    if image_cluster['clusterid'][k]==4:
        for dirname, _, filenames in os.walk('../input/datasetiitisocac'):
            for filename in filenames:
                if (filename==image_cluster['image'][k]):
                    shutil.copy(os.path.join(dirname,image_cluster['image'][k]), os.path.join('clusterr4',image_cluster['image'][k]))
    

In [39]:
os.mkdir('clusterr5')


In [40]:
for k in range(len(image_cluster)):
    if image_cluster['clusterid'][k]==5:
        for dirname, _, filenames in os.walk('../input/datasetiitisocac'):
            for filename in filenames:
                if (filename==image_cluster['image'][k]):
                    shutil.copy(os.path.join(dirname,image_cluster['image'][k]), os.path.join('clusterr5',image_cluster['image'][k]))
    

In [41]:
os.mkdir('clusterr6')


In [42]:
for k in range(len(image_cluster)):
    if image_cluster['clusterid'][k]==6:
        for dirname, _, filenames in os.walk('../input/datasetiitisocac'):
            for filename in filenames:
                if (filename==image_cluster['image'][k]):
                    shutil.copy(os.path.join(dirname,image_cluster['image'][k]), os.path.join('clusterr6',image_cluster['image'][k]))
    

In [43]:
os.mkdir('clusterr7')


In [44]:
for k in range(len(image_cluster)):
    if image_cluster['clusterid'][k]==7:
        for dirname, _, filenames in os.walk('../input/datasetiitisocac'):
            for filename in filenames:
                if (filename==image_cluster['image'][k]):
                    shutil.copy(os.path.join(dirname,image_cluster['image'][k]), os.path.join('clusterr7',image_cluster['image'][k]))
    

In [45]:
os.mkdir('clusterr8')


In [46]:
for k in range(len(image_cluster)):
    if image_cluster['clusterid'][k]==8:
        for dirname, _, filenames in os.walk('../input/datasetiitisocac'):
            for filename in filenames:
                if (filename==image_cluster['image'][k]):
                    shutil.copy(os.path.join(dirname,image_cluster['image'][k]), os.path.join('clusterr8',image_cluster['image'][k]))
    

In [47]:
os.mkdir('clusterr9')

In [48]:
for k in range(len(image_cluster)):
    if image_cluster['clusterid'][k]==9:
        for dirname, _, filenames in os.walk('../input/datasetiitisocac'):
            for filename in filenames:
                if (filename==image_cluster['image'][k]):
                    shutil.copy(os.path.join(dirname,image_cluster['image'][k]), os.path.join('clusterr9',image_cluster['image'][k]))
    

In [49]:
count_0=0
total_0=0
for k in range(len(image_cluster)):
    if image_cluster['clusterid'][k]==0:
        for dirname, _, filenames in os.walk('../input/datasetiitisocac'):
            for filename in filenames:
                if (filename==image_cluster['image'][k]):
                    print(dirname)
                    total_0=total_0+1
                    if (dirname=='../input/datasetiitisocac/caterpillar'):
                        count_0= count_0+1
                        
print (count_0)
print(total_0)

../input/datasetiitisocac/elephant
../input/datasetiitisocac/cow
../input/datasetiitisocac/dog
../input/datasetiitisocac/cow
../input/datasetiitisocac/deer
../input/datasetiitisocac/deer
../input/datasetiitisocac/deer
../input/datasetiitisocac/deer
../input/datasetiitisocac/deer
../input/datasetiitisocac/deer
../input/datasetiitisocac/deer
../input/datasetiitisocac/deer
../input/datasetiitisocac/dog
../input/datasetiitisocac/elephant
../input/datasetiitisocac/deer
../input/datasetiitisocac/deer
../input/datasetiitisocac/dog
../input/datasetiitisocac/deer
../input/datasetiitisocac/dog
../input/datasetiitisocac/deer
../input/datasetiitisocac/dog
../input/datasetiitisocac/elephant
../input/datasetiitisocac/elephant
../input/datasetiitisocac/deer
../input/datasetiitisocac/cat
../input/datasetiitisocac/deer
../input/datasetiitisocac/deer
../input/datasetiitisocac/deer
../input/datasetiitisocac/deer
../input/datasetiitisocac/deer
../input/datasetiitisocac/deer
../input/datasetiitisocac/deer


In [50]:
count_1=0
total_1=0
for k in range(len(image_cluster)):
    if image_cluster['clusterid'][k]==1:
        for dirname, _, filenames in os.walk('../input/datasetiitisocac'):
            for filename in filenames:
                if (filename==image_cluster['image'][k]):
                    print(dirname)
                    total_1=total_1+1
                    if (dirname=='../input/datasetiitisocac/elephant'):
                        count_1=count_1+1
print(count_1) 
print(total_1)

../input/datasetiitisocac/butterfly
../input/datasetiitisocac/caterpillar
../input/datasetiitisocac/dolphin
../input/datasetiitisocac/cow
../input/datasetiitisocac/caterpillar
../input/datasetiitisocac/butterfly
../input/datasetiitisocac/dog
../input/datasetiitisocac/dog
../input/datasetiitisocac/chimpanzee
../input/datasetiitisocac/elephant
../input/datasetiitisocac/butterfly
../input/datasetiitisocac/deer
../input/datasetiitisocac/butterfly
../input/datasetiitisocac/caterpillar
../input/datasetiitisocac/cat
../input/datasetiitisocac/caterpillar
../input/datasetiitisocac/butterfly
../input/datasetiitisocac/deer
../input/datasetiitisocac/caterpillar
../input/datasetiitisocac/butterfly
../input/datasetiitisocac/caterpillar
../input/datasetiitisocac/butterfly
../input/datasetiitisocac/elephant
../input/datasetiitisocac/dog
../input/datasetiitisocac/caterpillar
../input/datasetiitisocac/dog
../input/datasetiitisocac/butterfly
../input/datasetiitisocac/caterpillar
../input/datasetiitisocac

In [51]:
count_2=0
total_2=0
for k in range(len(image_cluster)):
    if image_cluster['clusterid'][k]==2:
        for dirname, _, filenames in os.walk('../input/datasetiitisocac'):
            for filename in filenames:
                if (filename==image_cluster['image'][k]):
                    print(dirname)
                    total_2=total_2+1
                    if (dirname=='../input/datasetiitisocac/chimpanzee'):
                        count_2=count_2+1
print(count_2) 
print(total_2)

../input/datasetiitisocac/dolphin
../input/datasetiitisocac/dog
../input/datasetiitisocac/dog
../input/datasetiitisocac/dog
../input/datasetiitisocac/dolphin
../input/datasetiitisocac/dolphin
../input/datasetiitisocac/dolphin
../input/datasetiitisocac/dolphin
../input/datasetiitisocac/dolphin
../input/datasetiitisocac/dolphin
../input/datasetiitisocac/dolphin
../input/datasetiitisocac/dolphin
../input/datasetiitisocac/dolphin
../input/datasetiitisocac/dolphin
../input/datasetiitisocac/dolphin
../input/datasetiitisocac/dolphin
../input/datasetiitisocac/dolphin
../input/datasetiitisocac/caterpillar
../input/datasetiitisocac/dolphin
../input/datasetiitisocac/dolphin
../input/datasetiitisocac/dolphin
../input/datasetiitisocac/dolphin
../input/datasetiitisocac/dolphin
../input/datasetiitisocac/dolphin
../input/datasetiitisocac/elephant
../input/datasetiitisocac/dog
../input/datasetiitisocac/dolphin
../input/datasetiitisocac/dolphin
../input/datasetiitisocac/dog
../input/datasetiitisocac/dol

In [52]:
count_3=0
total_3=0
for k in range(len(image_cluster)):
    if image_cluster['clusterid'][k]==3:
        for dirname, _, filenames in os.walk('../input/datasetiitisocac'):
            for filename in filenames:
                if (filename==image_cluster['image'][k]):
                    print(dirname)
                    total_3=total_3+1
                    if (dirname=='../input/datasetiitisocac/butterfly'):
                        count_3=count_3+1
print(count_3)   
print (total_3)

../input/datasetiitisocac/sparrow
../input/datasetiitisocac/sparrow
../input/datasetiitisocac/sparrow
../input/datasetiitisocac/sparrow
../input/datasetiitisocac/sparrow
../input/datasetiitisocac/sparrow
../input/datasetiitisocac/sparrow
../input/datasetiitisocac/sparrow
../input/datasetiitisocac/sparrow
../input/datasetiitisocac/sparrow
../input/datasetiitisocac/sparrow
../input/datasetiitisocac/sparrow
../input/datasetiitisocac/sparrow
../input/datasetiitisocac/sparrow
../input/datasetiitisocac/sparrow
../input/datasetiitisocac/sparrow
../input/datasetiitisocac/sparrow
../input/datasetiitisocac/sparrow
../input/datasetiitisocac/sparrow
../input/datasetiitisocac/sparrow
../input/datasetiitisocac/sparrow
../input/datasetiitisocac/sparrow
../input/datasetiitisocac/sparrow
../input/datasetiitisocac/sparrow
../input/datasetiitisocac/sparrow
../input/datasetiitisocac/sparrow
../input/datasetiitisocac/sparrow
../input/datasetiitisocac/sparrow
../input/datasetiitisocac/sparrow
../input/datas

In [53]:
count_4=0
total_4=0
for k in range(len(image_cluster)):
    if image_cluster['clusterid'][k]==4:
        for dirname, _, filenames in os.walk('../input/datasetiitisocac'):
            for filename in filenames:
                if (filename==image_cluster['image'][k]):
                    print(dirname)
                    total_4=total_4+1
                    if (dirname=='../input/datasetiitisocac/dolphin'):
                        count_4=count_4+1
print(count_4)     
print(total_4)
              

../input/datasetiitisocac/chimpanzee
../input/datasetiitisocac/chimpanzee
../input/datasetiitisocac/chimpanzee
../input/datasetiitisocac/chimpanzee
../input/datasetiitisocac/chimpanzee
../input/datasetiitisocac/chimpanzee
../input/datasetiitisocac/chimpanzee
../input/datasetiitisocac/chimpanzee
../input/datasetiitisocac/chimpanzee
../input/datasetiitisocac/chimpanzee
../input/datasetiitisocac/chimpanzee
../input/datasetiitisocac/chimpanzee
../input/datasetiitisocac/chimpanzee
../input/datasetiitisocac/chimpanzee
../input/datasetiitisocac/chimpanzee
../input/datasetiitisocac/chimpanzee
../input/datasetiitisocac/chimpanzee
../input/datasetiitisocac/chimpanzee
../input/datasetiitisocac/chimpanzee
../input/datasetiitisocac/chimpanzee
../input/datasetiitisocac/chimpanzee
../input/datasetiitisocac/chimpanzee
../input/datasetiitisocac/chimpanzee
../input/datasetiitisocac/chimpanzee
../input/datasetiitisocac/chimpanzee
../input/datasetiitisocac/chimpanzee
../input/datasetiitisocac/chimpanzee
.

In [54]:
count_5=0
total_5=0
for k in range(len(image_cluster)):
    if image_cluster['clusterid'][k]==5:
        for dirname, _, filenames in os.walk('../input/datasetiitisocac'):
            for filename in filenames:
                if (filename==image_cluster['image'][k]):
                    print(dirname)
                    total_5=total_5+1
                    if (dirname=='../input/datasetiitisocac/dog'):
                        count_5=count_5+1
print(count_5)    
print(total_5)

../input/datasetiitisocac/elephant
../input/datasetiitisocac/elephant
../input/datasetiitisocac/elephant
../input/datasetiitisocac/elephant
../input/datasetiitisocac/elephant
../input/datasetiitisocac/elephant
../input/datasetiitisocac/elephant
../input/datasetiitisocac/elephant
../input/datasetiitisocac/elephant
../input/datasetiitisocac/elephant
../input/datasetiitisocac/elephant
../input/datasetiitisocac/elephant
../input/datasetiitisocac/elephant
../input/datasetiitisocac/elephant
../input/datasetiitisocac/elephant
../input/datasetiitisocac/elephant
../input/datasetiitisocac/elephant
../input/datasetiitisocac/elephant
../input/datasetiitisocac/elephant
../input/datasetiitisocac/elephant
../input/datasetiitisocac/elephant
../input/datasetiitisocac/elephant
../input/datasetiitisocac/elephant
../input/datasetiitisocac/elephant
../input/datasetiitisocac/elephant
../input/datasetiitisocac/elephant
../input/datasetiitisocac/elephant
../input/datasetiitisocac/elephant
../input/datasetiiti

In [55]:
count_6=0
total_6=0
for k in range(len(image_cluster)):
    if image_cluster['clusterid'][k]==6:
        for dirname, _, filenames in os.walk('../input/datasetiitisocac'):
            for filename in filenames:
                if (filename==image_cluster['image'][k]):
                    print(dirname)
                    total_6=total_6+1
                    if (dirname=='../input/datasetiitisocac/cow'):
                        count_6=count_6+1
print(count_6)
print(total_6)

../input/datasetiitisocac/dog
../input/datasetiitisocac/dog
../input/datasetiitisocac/dog
../input/datasetiitisocac/dog
../input/datasetiitisocac/dog
../input/datasetiitisocac/dog
../input/datasetiitisocac/dog
../input/datasetiitisocac/dog
../input/datasetiitisocac/dog
../input/datasetiitisocac/dog
../input/datasetiitisocac/dog
../input/datasetiitisocac/dog
../input/datasetiitisocac/dog
../input/datasetiitisocac/dog
../input/datasetiitisocac/dog
../input/datasetiitisocac/dog
../input/datasetiitisocac/dog
../input/datasetiitisocac/dog
../input/datasetiitisocac/dog
../input/datasetiitisocac/dog
../input/datasetiitisocac/dog
../input/datasetiitisocac/dog
../input/datasetiitisocac/dog
../input/datasetiitisocac/dog
../input/datasetiitisocac/dog
../input/datasetiitisocac/dog
0
26


In [56]:
count_7=0
total_8=0
for k in range(len(image_cluster)):
    if image_cluster['clusterid'][k]==7:
        for dirname, _, filenames in os.walk('../input/datasetiitisocac'):
            for filename in filenames:
                if (filename==image_cluster['image'][k]):
                    print(dirname)
                    total_8=total_8+1
                    if (dirname=='../input/datasetiitisocac/sparrow'):
                        count_7=count_7+1
print(count_7) 
print(total_8)

../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
../input/datasetiitisocac/dog
../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
../input/datasetiitisocac/dog
../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
../input/datasetiitisocac/dog
../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
0
22


In [57]:
count_8=0
total_8=0
for k in range(len(image_cluster)):
    if image_cluster['clusterid'][k]==8:
        for dirname, _, filenames in os.walk('../input/datasetiitisocac'):
            for filename in filenames:
                if (filename==image_cluster['image'][k]):
                    print(dirname)
                    total_8=total_8+1
                    if (dirname=='../input/datasetiitisocac/deer'):
                        count_8=count_8+1
print(count_8)        
print(total_8)                   

../input/datasetiitisocac/cow
../input/datasetiitisocac/cow
../input/datasetiitisocac/cow
../input/datasetiitisocac/cow
../input/datasetiitisocac/cow
../input/datasetiitisocac/dog
../input/datasetiitisocac/cow
../input/datasetiitisocac/cow
../input/datasetiitisocac/cow
../input/datasetiitisocac/cow
../input/datasetiitisocac/cow
../input/datasetiitisocac/cow
../input/datasetiitisocac/cow
../input/datasetiitisocac/cow
../input/datasetiitisocac/cow
../input/datasetiitisocac/cow
../input/datasetiitisocac/cow
../input/datasetiitisocac/cow
../input/datasetiitisocac/cow
../input/datasetiitisocac/cow
../input/datasetiitisocac/cow
../input/datasetiitisocac/cow
../input/datasetiitisocac/cow
../input/datasetiitisocac/cow
../input/datasetiitisocac/cow
../input/datasetiitisocac/cow
../input/datasetiitisocac/cow
../input/datasetiitisocac/cow
../input/datasetiitisocac/cow
../input/datasetiitisocac/cow
../input/datasetiitisocac/cow
../input/datasetiitisocac/cow
../input/datasetiitisocac/dog
../input/d

In [58]:
count_9=0
total_9=0
for k in range(len(image_cluster)):
    if image_cluster['clusterid'][k]==9:
        for dirname, _, filenames in os.walk('../input/datasetiitisocac'):
            for filename in filenames:
                if (filename==image_cluster['image'][k]):
                    print(dirname)
                    total_9=total_9+1
                    if (dirname=='../input/datasetiitisocac/cat'):
                        count_9=count_9+1
print(count_9) 
print(total_9)

../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
../input/datasetiitisocac/dog
../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
../input/datasetiitisocac/cat
31
32


**The total number of correctly classified images :
501/600= 0.8350**

In [59]:
#images are clustered and copied into their respective folders in the output directory.

#Approach
#1 Defined a function and used Pre-trained model Inception V3 to obtain the features of the image (corr to the name)
#2 Merged the two columns into a dataframe 
#3 Shuffled the dataframe so that the model does not learn anything from the order of the images
#4 Used KMeans algorithm to cluster the data
#5 Made 10 directories to store the clustered images
#6 Copied the  images into their respective folders 
## To improvise the model, applied PCA and the score improved from 0.7317 to 0.8350

#TO DO

#1Assign labels of the images
#2 Get the percentage of data currectly classified
#3 Download the clustered images 
#4 Improvise the model(using image augmentation,etc.) 


